import { Footer } from "@/components/Shared/Footer";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./lib/Providers";

export const metadata: Metadata = {
  title: "Kinsley - Hotel & Restaurant",
  description: "generated by Mukbul Hasan Razib",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="bg-base-100">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
